export const EMAIL_CHANGED = 'EMAIL_CHANGED'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'

export const SHOW_IMAGE = 'SHOW_IMAGE'
export const ADD_PICTURE = 'ADD_PICTURE'
export const SHOW_IMAGES = 'SHOW_IMAGES'
